const rarity = [
    {
      name: "Common",
      value: 0,
      texts: ["Bruh", "Trash", "Go pack p2w at pets go", "Cry", "Leave", "L"],
      colors: ["#AAAAAA"],
    },
    {
      name: "Uncommon",
      value: 1,
      texts: ["Unlucky", "oh my god i am a noob", "uncommon steak?", "Little L"],
      colors: ["#CC3333"],
    },
    {
      name: "Rare",
      value: 2,
      texts: ["Bad try", "Microscopic L", "This cant be rare"],
      colors: ["#33CC33"],
    },
    {
      name: "Super Rare",
      value: 3,
      texts: [
        "Good try",
        "Rare=Ender but Ender is an arabic name so dynamike is super arab and you too?",
        "Close to getting El primo oh you have it?",
      ],
      colors: ["#3333CC"],
    },
    {
      name: "Epic",
      value: 4,
      texts: ["VAV", "VAVAV", "i WANT MINIMUM EXTRA SAUCE++","HAHA tarhanaman noob trash"],
      colors: ["#CCCC33"],
    },
    {
      name: "Super Epic",
      value: 5,
      texts: ["Lucky", "WOW you luck itself actually noob"],
      colors: ["#CC33CC"],
    },
    {
      name: "Legendary",
      value: 6,
      texts: ["I want my meat legendary", "Cat la best", "French b"],
      colors: ["#33CCCC"],
    },
    {
      name: "Mythical",
      value: 7,
      texts: ["Mythic"],
      colors: ["#B45F06"],
    },
    {
      name: "Godly",
      value: 8,
      texts: ["What is better"],
      colors: ["#9932CC"],
    },
    {
      name: "Cheesy",
      value: 9,
      texts: ["Why this better"],
      colors: ["#888888"],
    },
    {
      name: "Extra Sauce",
      value: 10,
      texts: ["What the 2.2.2.2.2.2.2.2.2.2"],
      colors: ["#A9A9A9"],
    },
    {
      name: "Common+",
      value: 11,
      texts: ["?+?"],
      colors: ["#D2691E"],
    },
    {
      name: "Uncommon+",
      value: 12,
      texts: ["Infinite loop?"],
      colors: ["#800000"],
    },
    {
      name: "Rare+",
      value: 13,
      texts: ["I want huge pet"],
      colors: ["#339933"],
    },
    {
      name: "Super Rare+",
      value: 14,
      texts: ["Banana"],
      colors: ["#333399"],
    },
    {
      name: "Epic+",
      value: 15,
      texts: ["Gus gus op"],
      colors: ["#999933"],
    },
    {
      name: "Super Epic+",
      value: 16,
      texts: ["stop it..."],
      colors: ["#990033"],
    },
    {
      name: "Legendary+",
      value: 17,
      texts: ["How did we get here"],
      colors: ["#FF6347"],
    },
    {
      name: "Mythical+",
      value: 18,
      texts: ["Nibble"],
      colors: ["#CD853F"],
    },
    {
      name: "Godly+",
      value: 19,
      texts: ["Near end"],
      colors: ["#FF77FF"],
    },
    {
      name: "Cheesy+",
      value: 20,
      texts: ["-1 step ahead"],
      colors: ["#FFD700"],
    },
    {
      name: "Extra Sauce+",
      value: 21,
      texts: ["The End????????", "Na' bro"],
      colors: ["#FFA500"],
    },
  ];
  