const rarity = [
  {
    name: "Common",
    value: 0,
    texts: ["Bruh", "Trash", "Go pack p2w at pets go", "Cry", "Leave", "L"],
    colors: ["#FFFFFF"],
  },
  {
    name: "Uncommon",
    value: 1,
    texts: ["Unlucky", "oh my god i am a noob", "uncommon steak?", "Little L"],
    colors: ["#FF0000"],
  },
  {
    name: "Rare",
    value: 2,
    texts: ["Bad try", "Microscobic L", "This cant be rare"],
    colors: ["#00FF00"],
  },
  {
    name: "Super Rare",
    value: 3,
    texts: [
      "Good try",
      "Rare=Ender but Ender is an arabic name so dynamike is super arab and you too?",
      "Close to getting El primo oh you have it?",
    ],
    colors: ["#0000FF"],
  },
  {
    name: "Epic",
    value: 4,
    texts: ["VAV", "VAVAV", "i WANT MINIMUM EXTRA SAUCE++","HAHA tarhanaman noob trash"],
    colors: ["#FFFF00"],
  },
  {
    name: "Super Epic",
    value: 5,
    texts: ["Lucky", "WOW you luck itself actuaaly noob"],
    colors: ["#FF00FF"],
  },
  {
    name: "Legendary",
    value: 6,
    texts: ["I want my meat legendary", "Cat la best", "French b"],
    colors: ["#00FFFF"],
  },
  {
    name: "Mythical",
    value: 7,
    texts: ["Mthic"],
    colors: ["#FFA500"],
  },
  {
    name: "Godly",
    value: 8,
    texts: ["What is better"],
    colors: ["#800080"],
  },
  {
    name: "Cheesy",
    value: 9,
    texts: ["Why this better"],
    colors: ["#808080"],
  },
  {
    name: "Extra Sauce",
    value: 10,
    texts: ["What the 2.2.2.2.2.2.2.2.2.2"],
    colors: ["#C0C0C0"],
  },
  {
    name: "Common+",
    value: 11,
    texts: ["?+?"],
    colors: ["#A52A2A"],
  },
  {
    name: "Uncommon+",
    value: 12,
    texts: ["Infinite loop?"],
    colors: ["#800000"],
  },
  {
    name: "Rare+",
    value: 13,
    texts: ["I want huge pet"],
    colors: ["#008000"],
  },
  {
    name: "Super Rare+",
    value: 14,
    texts: ["Banana"],
    colors: ["#000080"],
  },
  {
    name: "Epic+",
    value: 15,
    texts: ["Gus gus op"],
    colors: ["#808000"],
  },
  {
    name: "Super Epic+",
    value: 16,
    texts: ["stop it..."],
    colors: ["#800000"],
  },
  {
    name: "Legendary+",
    value: 17,
    texts: ["How did we get here"],
    colors: ["#FF6347"],
  },
  {
    name: "Mythical+",
    value: 18,
    texts: ["Nibble"],
    colors: ["#FF4500"],
  },
  {
    name: "Godly+",
    value: 19,
    texts: ["Near end"],
    colors: ["#FF69B4"],
  },
  {
    name: "Cheesy+",
    value: 20,
    texts: ["-1 step ahead"],
    colors: ["#FFD700"],
  },
  {
    name: "Extra Sauce+",
    value: 21,
    texts: ["The End????????", "Na' bro"],
    colors: ["#FF8C00"],
  },
];
