name: Update Version Info

on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest commit hash
        id: get_commit
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Check and increment version number
        run: |
          # Check if version.v exists
          if [ -f version.v ]; then
            version=$(cat version.v)
            version=$((version + 1))
          else
            version=1
          fi
          echo "$version" > version.v
          echo "version=$version" >> $GITHUB_ENV

      - name: Create version.json with commit hash
        run: |
          echo "{ \"commitHash\": \"${{ env.commit_hash }}\"}" > version.json

      - name: Commit and push version.json and version.v
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.json version.v
          git commit -m "Update version files with the latest version and commit hash"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
